name: Playwright E2E Tests

on:
  deployment_status:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Log contents of github event
        run: |
          echo ${{ github.event.GITHUB_REF }}
          echo ${{ github.event.GITHUB_SHA }}

      - name: Restore browser cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.cache/ms-playwright
          key: playwright
          restore-keys: playwright

      - name: Install Browsers
        run: npx playwright install --with-deps

      - name: E2E tests
        run: yarn test:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

      - name: PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Playwright E2E Test Report
          message: |
            [E2E Test Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
